# Generated by Django 4.0.1 on 2022-01-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigpixel', '0002_pixeltrackingcode_tracking_code_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixeltrackingcodesite',
            name='tracking_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigpixel.pixeltrackingcode'),
        ),
    ]
